<?php
/**
 * @file
 *
 * Constant defintions.
 */

/**
 * Permission constants of Voicemail module
 */
define('VOICEMAIL_HAVE_MAILBOX_ACCESS', 'have voice mail box');
define('VOICEMAIL_ADMINISTER_MAILBOX', 'administer voice mail box');

/**
 * Field level constants to store the static field names.
 */
define('VOICEMAIL_GROUP_FIELD_NAME', 'group_voicemail_settings');
define('VOICEMAIL_AUDIO_FIELD_NAME', 'field_voicemail_audio_greeting');
define('VOICEMAIL_STATUS_FIELD_NAME', 'field_voicemail_status');
